# Generated by Django 4.2.6 on 2023-10-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_portfolio_project_talent_techstack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='remote',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
