# Generated by Django 4.2.6 on 2023-10-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_talent_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
