# Generated by Django 4.2.6 on 2023-10-31 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_degree_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='api',
            name='tech_stack',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='education',
        ),
        migrations.RemoveField(
            model_name='framework',
            name='tech_stack',
        ),
        migrations.RemoveField(
            model_name='language',
            name='tech_stack',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='tech_stack',
        ),
        migrations.RemoveField(
            model_name='project',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='tech_stack',
        ),
        migrations.RemoveField(
            model_name='versioncontrol',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='api',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='degree',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='framework',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='language',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platform',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talent',
            name='service',
            field=models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Accounting', 'Accounting'), ('Testing', 'Testing'), ('Home Aid', 'Home Aid')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='versioncontrol',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='TechStack',
        ),
    ]
