# Generated by Django 4.2.6 on 2023-11-01 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='users.talent'),
        ),
        migrations.AddField(
            model_name='degree',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degree', to='users.talent'),
        ),
        migrations.AddField(
            model_name='framework',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='framework', to='users.talent'),
        ),
        migrations.AddField(
            model_name='language',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language', to='users.talent'),
        ),
        migrations.AddField(
            model_name='platform',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='users.talent'),
        ),
        migrations.AddField(
            model_name='project',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.talent'),
        ),
        migrations.AddField(
            model_name='storage',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='users.talent'),
        ),
        migrations.AddField(
            model_name='versioncontrol',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_control', to='users.talent'),
        ),
    ]
