# Generated by Django 4.2.6 on 2023-11-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_organization_city_organization_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_title',
            new_name='company',
        ),
    ]
