# Generated by Django 4.2.6 on 2023-11-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_project_title_project_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='company',
            new_name='project_title',
        ),
    ]
