# Generated by Django 4.2.6 on 2023-11-01 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_company_project_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillStack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('talent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skillStack', to='users.talent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='framework',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='framework',
            name='user',
        ),
        migrations.RemoveField(
            model_name='language',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='language',
            name='user',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='user',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='versioncontrol',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='versioncontrol',
            name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_title',
            new_name='company',
        ),
        migrations.DeleteModel(
            name='API',
        ),
        migrations.DeleteModel(
            name='Framework',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.DeleteModel(
            name='VersionControl',
        ),
    ]
