# Generated by Django 4.2.6 on 2023-11-01 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_skillstack_type_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('Dutch', 'Dutch')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('social_media', models.CharField(blank=True, choices=[('Portfolio', 'Portfolio'), ('Blog', 'Blog'), ('Personal Webiste', 'Personal Webiste'), ('Behance', 'Behance'), ('LinkedIn', 'LinkedIn'), ('Whatsapp', 'Whatsapp'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('TikTok', 'TikTok'), ('Pinterest', 'Pinterest')], max_length=30, null=True)),
                ('media_link', models.CharField(blank=True, max_length=255, null=True)),
                ('talent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='users.talent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
