# Generated by Django 4.2.6 on 2023-11-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_language_language_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
