# Generated by Django 4.2.6 on 2023-11-02 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_technologiesused_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='users.talent'),
        ),
    ]
