# Generated by Django 4.2.6 on 2023-11-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='remote',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
    ]
