# Generated by Django 4.2.6 on 2023-11-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_talent_remote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
