# Generated by Django 4.2.6 on 2023-11-02 13:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_degree_end_date_alter_degree_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('Resume', 'Resume'), ('Ghana Card', 'Ghana Card'), ('Voters ID', 'Voters ID'), ('Passport', 'Passport')], max_length=25, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='users_profile/')),
                ('talent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identityCards', to='users.talent')),
            ],
        ),
    ]
