# Generated by Django 4.2.6 on 2023-11-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_identityfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='users_fileUploads/'),
        ),
    ]
