# Generated by Django 4.2.6 on 2023-11-07 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='talent_id',
        ),
        migrations.AddField(
            model_name='manager',
            name='client',
            field=models.ManyToManyField(blank=True, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manager',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='slack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
