# Generated by Django 4.2.6 on 2023-11-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_manager_client_id_remove_manager_talent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
