# Generated by Django 4.2.6 on 2023-11-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_talent_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='media_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
