databases:
  - name: skilledhqbackend
    databaseName: djangodb
    user: skilledhqbackend

services:
  - type: web
    name: skilledhqbackend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn skilledhqbackend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: skilledhqbackend
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
