# Generated by Django 4.2.6 on 2023-11-03 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_role_description_file_cart_service_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='title',
        ),
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='hourly_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='order_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.order'),
        ),
        migrations.AddField(
            model_name='contract',
            name='role_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='role_description_file',
            field=models.FileField(blank=True, null=True, upload_to='role_description_files/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='service',
            field=models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Accounting', 'Accounting'), ('Testing', 'Testing'), ('Home Aid', 'Home Aid')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(blank=True, choices=[('CONTRACT', 'CONTRACT'), ('FULL TIME', 'FULL TIME'), ('PART TIME', 'PART TIME')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='working_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='talent_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContractFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('contract', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('client_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ID', to=settings.AUTH_USER_MODEL)),
                ('talent_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_ID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
