# Generated by Django 4.2.6 on 2023-11-04 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_contract_contract_remove_contract_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('service', models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Accounting', 'Accounting'), ('Testing', 'Testing'), ('Home Aid', 'Home Aid')], max_length=255, null=True)),
                ('expertise', models.CharField(blank=True, max_length=255, null=True)),
                ('expertise_unlisted', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_to_start_work', models.CharField(blank=True, choices=[('Less than 1 week', 'Less than 1 week'), ('1 to 4 weeks', '1 to 4 weeks'), ('1 to 3 months', '1 to 3 months'), ('3 to 6 months', '3 to 6 months'), ('Longer than 6 months', 'Longer than 6 months'), ("I'll decide later", "I'll decide later")], max_length=30, null=True)),
                ('time_commitment', models.CharField(blank=True, choices=[('Full Time (FT)', 'Full Time (FT)'), ('Part Time (PT)', 'Part Time (PT)'), ("I'll decide later", "I'll decide later")], max_length=20, null=True)),
                ('in_office', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('remote', models.CharField(blank=True, max_length=255, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
            ],
        ),
    ]
