# Generated by Django 4.2.6 on 2023-11-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_talentapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentapplication',
            name='remote',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
    ]
