# Generated by Django 4.2.6 on 2023-11-06 13:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_duration_of_hire_alter_cart_project_type_and_more'),
        ('company', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_details', to='company.contractfiles'),
        ),
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.CharField(blank=True, choices=[('CONTRACT', 'CONTRACT'), ('FULL TIME', 'FULL TIME'), ('PART TIME', 'PART TIME')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='RoleDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('order_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='cart.order')),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='company.qualification')),
                ('responsibility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='company.responsibility')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='role_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.roledescription'),
        ),
    ]
