# Generated by Django 4.2.6 on 2023-11-06 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_qualification_responsibility_contract_contract_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roledescription',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='roledescription',
            name='responsibility',
        ),
        migrations.AddField(
            model_name='qualification',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='company.roledescription'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibility', to='company.roledescription'),
        ),
        migrations.AlterField(
            model_name='talentapplication',
            name='expertise',
            field=models.CharField(blank=True, choices=[('Software Development', 'Software Development'), ('Salesforce Administration', 'Salesforce Administration'), ('Quality Assurance (QA)', 'Quality Assurance (QA)'), ('Cloud Architecture', 'Cloud Architecture'), ('Software Testing', 'Software Testing'), ('Penetration Testing', 'Penetration Testing'), ('Load and Stress Testing', 'Load and Stress Testing'), ('Test Automation', 'Test Automation'), ('Usability Testing', 'Usability Testing'), ('Financial Prowess', 'Financial Prowess'), ('Auditing & Compliance', 'Auditing & Compliance'), ('Tax Mastery', 'Tax Mastery'), ('Risk Management', 'Risk Management'), ('Financial Planning', 'Financial Planning'), ('Professional Care', 'Professional Care'), ('Personalized Services', 'Personalized Services'), ('Senior Care and Companionship', 'Senior Care and Companionship'), ('Home Security', 'Home Security'), ('Home Renovation and Accessibility Solutions', 'Home Renovation and Accessibility Solutions'), ('Not Stated', 'Not Stated')], max_length=255, null=True),
        ),
    ]
