# Generated by Django 4.2.6 on 2023-11-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_roledescription_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='order_ID',
        ),
    ]
