# Generated by Django 4.2.6 on 2023-11-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_contract_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='role',
            field=models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Accounting', 'Accounting'), ('Testing', 'Testing'), ('Home Aid', 'Home Aid')], max_length=50, null=True),
        ),
    ]
