# Generated by Django 4.2.6 on 2023-11-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_contract_talent_id_contract_talent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='remote',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
    ]
