# Generated by Django 4.2.6 on 2023-11-08 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0012_contract_remote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Accounting', 'Accounting'), ('Testing', 'Testing'), ('Home Aid', 'Home Aid')], max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='billing_receipts/')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_client', to=settings.AUTH_USER_MODEL)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_talent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
