# Generated by Django 4.2.6 on 2023-11-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='title',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
