# Generated by Django 4.2.6 on 2023-11-09 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_duration_of_hire_alter_cart_project_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0015_contractchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='talent_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_talent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SuggestedContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Accounting', 'Accounting'), ('Testing', 'Testing'), ('Home Aid', 'Home Aid')], max_length=20, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('client_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('order_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.order')),
                ('talent_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talent_suggested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
