# Generated by Django 4.2.6 on 2023-11-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_alter_suggestedcontract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
