# Generated by Django 4.2.6 on 2023-10-31 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Engineering", "Engineering"),
                            ("Accounting", "Accounting"),
                            ("Testing", "Testing"),
                            ("Home Aid", "Home Aid"),
                        ],
                        default="Engineering",
                        max_length=60,
                    ),
                ),
                (
                    "service_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "working_options",
                    models.CharField(
                        choices=[
                            ("Full Time (FT)", "Full Time (FT)"),
                            ("Part Time (PT)", "Part Time (PT)"),
                            ("I'll decide later", "I'll decide later"),
                        ],
                        default="Full Time (FT)",
                        max_length=60,
                    ),
                ),
                (
                    "working_hours",
                    models.IntegerField(
                        blank=True,
                        choices=[(60, 60), (30, 30), (40, 40), (20, 20)],
                        default=60,
                        null=True,
                    ),
                ),
                (
                    "remote",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="Yes",
                        max_length=60,
                    ),
                ),
                (
                    "unlisted_service_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "number_needed",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                ("role_description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cart.cart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="cart.order",
            ),
        ),
    ]
