# Generated by Django 4.2.6 on 2023-11-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_role_description_file_cart_service_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='project_type',
            field=models.CharField(choices=[('New Project', 'New Project'), ('Existing Project', 'Existing Project'), ('Looking to learn more about SkilledHQ', 'Looking to learn more about SkilledHQ')], default='Full Time (FT)', max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('Process Page', 'Process Page'), ('Cart Page', 'Cart Page')], max_length=20, null=True),
        ),
    ]
