# Generated by Django 4.2.6 on 2023-11-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_project_type_order_contact_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='duration_of_hire',
            field=models.CharField(choices=[('Less than 1 week', 'Less than 1 week'), ('1 to 4 weeks', '1 to 4 weeks'), ('1 to 3 months', '1 to 3 months'), ('Longer than 6 months', 'Longer than 6 months'), ("I'll decide later", "I'll decide later")], default='Less than 1 week', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='talent_start_time',
            field=models.CharField(choices=[('Immediately', 'Immediately'), ('In 1 to 2 weeks', 'In 1 to 2 weeks'), ('More than 2 weeks from now', 'More than 2 weeks from now'), ("I'll decide later", "I'll decide later")], default='Immediately', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Waiting Confirmation', 'Waiting Confirmation'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='project_type',
            field=models.CharField(choices=[('New Project', 'New Project'), ('Existing Project', 'Existing Project'), ("None of the above, I'm just looking to learn more about < SkilledHQ / >", "None of the above, I'm just looking to learn more about < SkilledHQ / >")], default='New Project', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('Process', 'Process'), ('Cart', 'Cart')], max_length=20, null=True),
        ),
    ]
